src/BackendBundle/Entity/Comment.php
<?php

namespace BackendBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use NewsBundle\Entity\News;
use Gedmo\Mapping\Annotation as Gedmo;

/**
 * Comment
 * @ORM\Table(name="comment_table")
 * @ORM\Entity(repositoryClass="BackendBundle\Entity\Repository\CommentRepository")
 */
class Comment
{
    /* YES / NO */
    const YES = 1;
    const NO = 0;
    /**
     * @var \DateTimeInterface|null
     *
     * @ORM\Column(name="publish_at", type="datetime", nullable=true)
     */
    protected $publishAt;
    /**
     * @var integer
     *
     * @ORM\Column(name="id", type="integer", nullable=false)
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="IDENTITY")
     */
    private $id;
    /**
     * @var integer
     *
     * @ORM\Column(name="show_on_website", type="integer", nullable=false)
     */
    private $showOnWebsite = self::YES;
    /**
     * @var string
     *
     * @ORM\Column(name="name", type="string", length=255, nullable=true)
     */
    private $name;
    /**
     * @var string
     *
     * @ORM\Column(name="content", type="text", nullable=true)
     */
    private $content;
    /**
     * @ORM\ManyToOne(targetEntity="NewsBundle\Entity\News", inversedBy="comments")
     * @ORM\JoinColumns({
     *   @ORM\JoinColumn(name="news_id", referencedColumnName="id", onDelete="SET NULL")
     * })
     */
    private $news;

    /**
     * @return array|mixed
     */
    public static function yesOrNo()
    {
        return [
            self::YES => "Да",
            self::NO => "Нет"
        ];
    }

    /**
     * @return array|mixed
     */
    public static function yesOrNoForm()
    {
        return [
            "form.yes" => self::YES,
            "form.no" => self::NO,
        ];
    }

    public function __toString()
    {
        return (string)$this->translate()->getTitle();
    }

    /**
     * Get id
     *
     * @return integer
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * @return string
     */
    public function getName(): string
    {
        return $this->name;
    }

    /**
     * @param string $name
     *
     * @return $this
     */
    public function setName(string $name)
    {
        $this->name = $name;

        return $this;
    }

    /**
     * @return string
     */
    public function getContent(): string
    {
        return $this->content;
    }

    /**
     * @param string $content
     *
     * @return $this
     */
    public function setContent(string $content)
    {
        $this->content = $content;

        return $this;
    }

    /**
     * Get showOnWebsite
     *
     * @return integer
     */
    public function getShowOnWebsite()
    {
        return $this->showOnWebsite;
    }

    /**
     * Set showOnWebsite
     *
     * @param integer $showOnWebsite
     *
     * @return $this
     */
    public function setShowOnWebsite($showOnWebsite)
    {
        $this->showOnWebsite = $showOnWebsite;

        return $this;
    }

    /**
     * @return News
     */
    public function getNews()
    {
        return $this->news;
    }

    /**
     * @param News $news
     */
    public function setNews(News $news)
    {
        $this->news = $news;
    }

    public function getPublishAt()
    {
        if (!$this->publishAt) {
            self::setPublishAt(null);
        }

        return $this->publishAt->format('d-m-Y');
    }
    public function getPublishAtWithTime()
    {
        if (!$this->publishAt) {
            self::setPublishAt(null);
        }

        return $this->publishAt->format('H:i, Y-m-d');
    }


    public function setPublishAt($publishAt): void
    {
        if (is_null($publishAt)) {
            $this->publishAt = new \DateTime();
        } else {
            $this->publishAt = new \DateTime($publishAt);
        }
    }
}

src/FrontendBundle/Controller/FrontendController.php
<?php

namespace FrontendBundle\Controller;

use ComponentBundle\Utils\BreadcrumbsGenerator;
use NewsBundle\Entity\News;
use SeoBundle\Entity\SeoPage;
use StaticBundle\Entity\StaticPage;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Doctrine\ORM\EntityManagerInterface;

/**
 * @author Ihor Drevetskyi <ihor.drevetskyi@gmail.com>
 */
final class FrontendController extends Controller
{
    private function helperForStaticPage(BreadcrumbsGenerator $breadcrumbsGenerator, EntityManagerInterface $em, $name, $routeName)
    {
        $static = $em->getRepository(StaticPage::class)->getStaticPageBySystemName($name);

        if (empty($static)) {
            return $this->redirectToRoute('frontend_homepage');
        }

        $breadcrumbsArr = [];
        $seoHomepage = $em->getRepository(SeoPage::class)->getSeoForPageBySystemName('homepage');
        $breadcrumbsArr['frontend_homepage'][] = [
            'parameters' => [],
            'title' => (!empty($seoHomepage) and !empty($seoHomepage->breadcrumb)) ? $seoHomepage->breadcrumb : ''
        ];

        $seo = $static->getSeo()->getSeoForPage();
        $breadcrumbsArr[$routeName][] = [
            'parameters' => [],
            'title' => (!empty($seo) and !empty($seo->breadcrumb)) ? $seo->breadcrumb : ''
        ];

        $breadcrumbs = $breadcrumbsGenerator->generateBreadcrumbs($breadcrumbsArr);

        return $this->render('frontend/'.$name.'/index.html.twig', [
            'seo' => $seo,
            'page' => $static,
            'breadcrumbs' => $breadcrumbs,
        ]);
    }

    public function newsFeedAction(EntityManagerInterface $em){
        $newsFeed = $em->getRepository(News::class)->getLimitElements(10);
        return $this->render('frontend/news/_newsFeed.html.twig', [
            'newsFeed' => $newsFeed,
        ]);
    }
}

templates/frontend/news/_element.html.twig
<li class="last-news__item news-item infinite-scroll__item">
    <div class="d-flex">
        <time class="news-item__date news-date" timestamp="">
            {{ item.publishAt|localizeddate('short', 'none', 'ru') }}
        </time>
        <a class="news-item__title" href="{{ path('frontend_news_show', {
            'slug': item.translations[item.defaultLocale].slug
        }) }}">{{ item.translate.title }}</a>
    </div>
    <p class="news-item__text">
        {{ item.translate.shortDescription }}
    </p>
</li>

templates/frontend/news/_newsFeed.html.twig
{% if newsFeed|length > 0 %}
    <h3 class="page__sub-subtitle">Лента новостей</h3>
    <div class="last-news">
        <ul class="last-news__list">
            {% for item in newsFeed %}
                {% if loop.first %}
                    <li class="last-news__item news-item">
                        <a rel="nofollow" class="news-item__img-wrap lazy-container"
                           href="{{ path('frontend_news_show', {
                               'slug': item.translations[item.defaultLocale].slug
                           }) }}">
                            <img class="b-lazy news-item__img"
                                 data-src="{{ asset(item.poster|json_decode.default_file|default(asset('bundles/upload/images/no-image-400.png'))) }}"
                                 alt="">
                        </a>
                        {% if item.newsCategory is not null %}
                            <a class="label news-item__label"
                               href="{{ path('frontend_news_category_show', {
                                   'slug':  item.newsCategory.translations[ item.newsCategory.defaultLocale].slug
                               }) }}">
                                {{ item.newsCategory.translate.title }}
                            </a>
                        {% endif %}
                        <div class="d-flex">
                            <time class="news-item__date news-date" timestamp="">{{ item.publishAt }}</time>
                            <a class="news-item__title" href="{{ path('frontend_news_show', {
                                'slug': item.translations[item.defaultLocale].slug
                            }) }}">
                                {{ item.translate.title }}
                            </a>
                        </div>
                        {% if item.translate.shortDescription is not null %}
                            <p class="news-item__text">
                                {{ item.translate.shortDescription }}
                            </p>
                        {% endif %}
                    </li>
                {% else %}
                    <li class="last-news__item news-item">
                        <div class="d-flex">
                            <time class="news-item__date news-date" timestamp="">{{ item.publishAt }}</time>
                            <a class="news-item__title" href="{{ path('frontend_news_show', {
                                'slug': item.translations[item.defaultLocale].slug
                            }) }}">
                                {{ item.translate.title }}
                            </a>
                        </div>
                    </li>
                {% endif %}
            {% endfor %}
        </ul>
    </div>
{% endif %}

templates/frontend/news/_news_paginated_elements.html.twig
{% for item in elements %}
    {% include 'frontend/news/_element.html.twig' with {
        'item': item,
    } %}
{% endfor %}
{% if isKnpPaginationRender == true %}
    {{ knp_pagination_render(elements) }}
{% endif %}

templates/frontend/news/_sidebar_news.html.twig
{% if news|length > 0 %}
    <h3 class="page__sub-subtitle">Лента новостей</h3>
    <div class="last-news">
        <ul class="last-news__list">
            {% for item in news %}
                {% if item.newsCategory %}
                    {% set url =  path('frontend_news_show', {
                        'slug': item.translations[item.defaultLocale].slug,
                        'categorySlug': item.newsCategory.translations[item.newsCategory.defaultLocale].slug,
                    }) %}
                {% else %}
                    {% set url =  path('frontend_news_show', {
                        'slug': item.translations[item.defaultLocale].slug,
                    }) %}
                {% endif %}
                {% if loop.first %}
                    <li class="last-news__item news-item">
                        {% if item.newsCategory %}
                            <a class="news-item__img-wrap lazy-container" href="{{ url }}">
                                <img class="b-lazy news-item__img"
                                     data-src="{{ asset(item.poster|json_decode.default_file|default(asset('bundles/upload/images/no-image-400.png'))) }}"
                                     alt="">
                            </a>
                            <a class="label news-item__label" href="{{ path('frontend_news_category_show', {
                                'slug': item.newsCategory.translations[item.newsCategory.defaultLocale].slug
                            }) }}">
                                {{ item.newsCategory.translate.title }}
                            </a>
                        {% else %}
                            <a class="news-item__img-wrap lazy-container" href="{{ url }}">
                                <img class="b-lazy news-item__img"
                                     data-src="{{ asset(item.poster|json_decode.default_file|default(asset('bundles/upload/images/no-image-400.png'))) }}"
                                     alt="">
                            </a>
                        {% endif %}

                        <div class="d-flex">
                            <time class="news-item__date news-date" timestamp="">{{ item.publishAt|localizeddate('short', 'none', 'ru') }}</time>
                            <a class="news-item__title" href="{{ url }}">
                                {{ item.translate.title }}
                            </a>
                        </div>
                        {% if item.translate.shortDescription is not null %}
                            <p class="news-item__text">{{ item.translate.shortDescription }}</p>
                        {% endif %}
                    </li>
                {% else %}
                    <li class="last-news__item news-item">
                        <div class="d-flex">
                            <time class="news-item__date news-date"
                                  timestamp="">{{ item.publishAt|localizeddate('short', 'none', 'ru') }}</time>
                            <a class="news-item__title" href="{{ url }}">
                                {{ item.translate.title }}
                            </a>
                        </div>
                    </li>
                {% endif %}
            {% endfor %}
        </ul>
    </div>
{% endif %}

templates/frontend/news/index.html.twig
{% extends 'base.html.twig' %}

{% block main %}
  {% include 'frontend/default/_breadcrumbs.html.twig' %}
  <div class="container">
    <div class="row">

      <div class="col-12 col-lg-8 single-news">
        <h1 class="page__title">
          {% include '@Seo/frontend/_h1.html.twig' %}
        </h1>

        {{ render(controller('FrontendBundle\\Controller\\DefaultController::initNewsCategorySliderAction', {
          'slug': ''
        })) }}


        <h3 class="page__sub-subtitle">Лента новостей</h3>
        <div class="last-news">
          <ul class="last-news__list infinite-scroll" data-itemSelector=".infinite-scroll__item">
            {{  render(controller('NewsBundle\\Controller\\Frontend\\NewsController::getNewsElementsByPageAction', {
              'page': 1, 'countInPage': 2, 'fromTwig': true
            })) }}
          </ul>
        </div>
      </div>

      <aside class="col-12 col-lg-4 sidebar sidebar--with-padding">
        {% include 'frontend/default/_sidebar_socials.html.twig' %}
        {{ render(controller('FrontendBundle\\Controller\\DefaultController::initSidebarBannerAction')) }}
        {{ render(controller('FrontendBundle\\Controller\\DefaultController::initSidebarNewsAction')) }}
      </aside>
    </div>
  </div>
  <section class="bnr-section">
    <div class="container">
      <a rel="nofollow" class="bnr bnr--small"
         style="background-image: linear-gradient(to right, #1D9CD8, #194382)"></a>
    </div>
  </section>
{% endblock %}

templates/frontend/news/show.html.twig
{% extends 'base.html.twig' %}

{% block main %}
    {% include 'frontend/default/_breadcrumbs.html.twig' %}

    <div class="container">
        <div class="row">
            <div class="col-12 col-lg-8 single-news">
                <h1 class="page__title">
                    {% include '@Seo/frontend/_h1.html.twig' %}
                </h1>
                <blockquote class="quote">
                    <time class="news-date" timestamp="">{{ element.publishAt }}</time>
                    {% if element.translate.shortDescription is not null %}
                        <p class="quote__text">{{ element.translate.shortDescription }}</p>
                    {% endif %}
                </blockquote>
                {#<div class="row">#}
                    {#<div class="slider hero-slider hero-slider--fluid--left owl-carousel single-news__slider">#}
                        {#<div class="hero" style="background-image: url(img/temp/hero-1.jpg)"></div>#}
                        {#<div class="hero" style="background-image: url(img/temp/hero-2.jpg)"></div>#}
                        {#<div class="hero" style="background-image: url(img/temp/hero-3.jpg)"></div>#}
                    {#</div>#}
                {#</div>#}

                {{ include('/frontend/homepage/_singleNewsSlider.html.twig', {
                  'newsSlider': newsSlider
                }) }}

                <div class="static-content">
                    {{ element.translate.description|raw }}
                </div>

                <h2 class="page__subtitle">Коментарии</h2>
                {{ form_start(commentForm) }}

                <div class="form__group">
                    {{ form_label(commentForm.name, null, {'label_attr': {'class': 'form__label'}}) }}
                    {{ form_widget(commentForm.name, {'attr': {'class': 'form__input form__input--line--single'}}) }}
                </div>

                <div class="form__group">
                    {{ form_label(commentForm.content, null, {'label_attr': {'class': 'form__label'}}) }}
                    {{ form_widget(commentForm.content, {'attr': {'class': 'form__input form__input--line--multi'}}) }}
                </div>


                    {#<div class="form__group">#}
                        {#<label class="form__label" for="name">Мое имя и фамилия*</label>#}
                        {#<input class="form__input form__input--line--single" id="name">#}
                    {#</div>#}
                    {#<div class="form__group">#}
                        {#<label class="form__label" for="message">Я пишу*</label>#}
                        {#<textarea class="form__input form__input--line--multi" id="message"></textarea>#}
                    {#</div>#}
                    <div class="form__group text-right">
                        <button class="btn">Отправить сообщение</button>
                    </div>
                {{ form_end(commentForm) }}
                <div class="comments single-news__comments">
                    {% for comment in comments %}
                        <div class="comments__item comment">
                            <div class="comment__img-wrap comment__img-wrap--with-img">
                                <img class="comment__img" src="{{ asset('bundles/frontend/img/temp/comments-1.png') }}"
                                     alt="">
                            </div>
                            <blockqoute class="comment__text"><cite class="comment__author">{{ comment.name }}</cite>
                                <br>
                                <time class="comment__date">{{ comment.publishAtWithTime }}</time>
                                <p>{{ comment.content }}</p>
                            </blockqoute>
                        </div>
                    {% endfor %}

                </div>
            </div>
            <aside class="col-12 col-lg-4 sidebar sidebar--with-padding">
                <div class="socials sidebar__socials">
                    <ul class="socials__list">
                        <div class="socials__item">
                            <a rel="nofollow" class="socials__link" href="javascript:void(0);">
                                <svg class="svg-icon socials__icon" role="img" title="youtube">
                                    <use xlink:href="{{ asset('bundles/frontend/img/icons/svg/sprite.symbol.svg') }}#youtube"></use>
                                </svg>
                            </a>
                        </div>
                        <div class="socials__item">
                            <a rel="nofollow" class="socials__link" href="javascript:void(0);">
                                <svg class="svg-icon socials__icon" role="img" title="twitter">
                                    <use xlink:href="{{ asset('bundles/frontend/img/icons/svg/sprite.symbol.svg') }}#twitter"></use>
                                </svg>
                            </a>
                        </div>
                        <div class="socials__item">
                            <a rel="nofollow" class="socials__link" href="javascript:void(0);">
                                <svg class="svg-icon socials__icon" role="img" title="instagram">
                                    <use xlink:href="{{ asset('bundles/frontend/img/icons/svg/sprite.symbol.svg') }}#instagram"></use>
                                </svg>
                            </a>
                        </div>
                        <div class="socials__item">
                            <a rel="nofollow" class="socials__link" href="javascript:void(0);">
                                <svg class="svg-icon socials__icon" role="img" title="facebook">
                                    <use xlink:href="{{ asset('bundles/frontend/img/icons/svg/sprite.symbol.svg') }}#facebook"></use>
                                </svg>
                            </a>
                        </div>
                    </ul>
                </div>
                <a rel="nofollow" class="bnr sidebar__bnr" href="javascript:void(0);">
                    <img src="{{ asset('bundles/frontend/img/temp/banner-2.jpg') }}">
                </a>
                {{ render(controller('FrontendBundle:Frontend:newsFeed')) }}
            </aside>
        </div>
    </div>
    <section class="bnr-section">
        <div class="container">
            <a class="bnr bnr--small" style="background-image: linear-gradient(to right, #1D9CD8, #194382)"></a>
        </div>
    </section>
{% endblock %}